import { GetStaticProps } from "next";
import Head from "next/head";
import React from "react";
import { AboutpageProps } from "../components/types/homepage";
import { Teacher } from "../components/types/aboutpage";
import PageTitle from "../components/elements/PageTitle";
import AboutPage from "../components/templates/AboutPage";
import Teachers from "../components/elements/Teachers";

interface Props {
  dataTeachers: Teacher[];
  dataAbout: AboutpageProps;
}

export default function About({ dataAbout, dataTeachers }: Props) {
  return (
    <div>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <PageTitle
        title={dataAbout.title}
        content={dataAbout.first_content_block}
      />
      <AboutPage data={dataAbout} />
      <Teachers data={dataTeachers} />
    </div>
  );
}

export const getStaticProps: GetStaticProps = async () => {
  const resAbout = await fetch("http://localhost:5001/about_page");
  const dataAbout: AboutpageProps = await resAbout.json();

  const resTeachers = await fetch("http://localhost:5001/teachers");
  const dataTeachers: Teacher[] = await resTeachers.json();

  return {
    props: { dataTeachers, dataAbout },
  };
};
