import { GetStaticProps } from "next";
import Head from "next/head";
import React from "react";
import PageTitle from "../components/elements/PageTitle";
import { ContactpageProps } from "../components/types/contactpage";
import ContactPage from "../components/templates/ContactPage";

interface Props {
  data: ContactpageProps;
}

export default function Contact({ data }: Props) {
  return (
    <div>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <PageTitle title={data.title} content={data.first_content_block} />
      <ContactPage {...data} />
    </div>
  );
}

export const getStaticProps: GetStaticProps = async () => {
  const res = await fetch("http://localhost:5001/contact_page");
  const data: ContactpageProps = await res.json();

  return {
    props: { data },
  };
};
