import { GetStaticProps } from "next";
import Head from "next/head";
import HeroSection from "../components/elements/HeroSection";
import AboutBlock from "../components/elements/AboutBlock";
import {
  AboutpageProps,
  FeaturedCourse,
  HomepageProps,
  Testimonial,
} from "../components/types/homepage";
import FeaturedCourses from "../components/elements/FeaturedCourses";
import Testimonials from "../components/elements/Testimonials";

interface Props {
  data: HomepageProps;
  dataAbout: AboutpageProps;
  dataFeaturedCourses: FeaturedCourse[];
  dataTestimonials: Testimonial[];
}

export default function Home({
  data,
  dataAbout,
  dataFeaturedCourses,
  dataTestimonials,
}: Props) {
  return (
    <div>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <HeroSection title={data.title} content={data.content} />
      <AboutBlock
        title={dataAbout.title}
        first_content_block={dataAbout.first_content_block}
        first_image={dataAbout.first_image}
      />
      <FeaturedCourses data={dataFeaturedCourses} />
      <Testimonials
        title={data.testimonials_title}
        content={data.testimonials_content}
        data={dataTestimonials}
      />
    </div>
  );
}

export const getStaticProps: GetStaticProps = async () => {
  // const res = await fetch("http://localhost:5001/homepage");
  // const data: HomepageProps = await res.json();

  // const resAbout = await fetch("http://localhost:5001/about_page");
  // const dataAbout: AboutpageProps = await resAbout.json();

  // const resFeaturedCourses = await fetch(
  //   "http://localhost:5001/courses?_start=1&_limit=3"
  // );
  // const dataFeaturedCourses: FeaturedCourse[] = await resFeaturedCourses.json();

  // const resTestimonials = await fetch("http://localhost:5001/testimonials");
  // const dataTestimonials: Testimonial[] = await resTestimonials.json();
  const [res, resAbout, resFeaturedCourses, resTestimonials] =
    await Promise.all([
      fetch("http://localhost:5001/homepage"),
      fetch("http://localhost:5001/about_page"),
      fetch("http://localhost:5001/courses?_start=1&_limit=3"),
      fetch("http://localhost:5001/testimonials"),
    ]);

  // const res = Promise.race([
  //   fetch("http://localhost:5001/homepage"),
  //   new Promise((resolve, reject) => {
  //     setTimeout(() => {
  //       resolve(true);
  //     }, 3000);
  //   }),
  // ]);

  const [data, dataAbout, dataFeaturedCourses, dataTestimonials] =
    await Promise.all([
      res.json(),
      resAbout.json(),
      resFeaturedCourses.json(),
      resTestimonials.json(),
    ]);

  return {
    props: { data, dataAbout, dataFeaturedCourses, dataTestimonials },
  };
};
